repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
