name: hcd-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - black=21.9b0
  - flake8=4.0.1
  - graphviz
  - imbalanced-learn
  - jupyter
  - matplotlib>=3.4
  - numpy>=1.21
  - opencv
  - pandas>=1.3
  - pillow
  - pre-commit=2.15.0
  - pydot
  - python=3.8
  - scikit-learn
  - seaborn
  - tensorboard
  - tensorflow-gpu>=2.4