name: hcd-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - imbalanced-learn
  - jupyter
  - matplotlib>=3.4
  - numpy>=1.21
  - opencv
  - pandas>=1.3
  - pydot
  - pillow
  - python=3.8
  - scikit-learn
  - seaborn
  - tensorboard
  - tensorflow-gpu>=2.4